### ISSUE TITLE
makefile mishandling many build variables

### ISSUE THREAD

**Issue by vapier** [chenhn123/wdt_util_src#4]
commit 4d13cf271760f845e0f9fc057a6fdd394d7155e3 tried to fix build flags, but it ended up breaking things more.  here is what it should look like:

* `CPP` should be `CXX`, but you should just delete it -- the default should be fine
* the flags in `CPPFLAGS` should be left in `CXXFLAGS`.  you should write it `CXXFLAGS ?= -Wall -g`.
* don't clobber `LDFLAGS`.  the empty definition is pointless, so just delete the line.
* the `INCLUDES` variable isn't a thing, so you should delete it.
* you're now missing `CXXFLAGS` in the compile/link stages.  just write:
```
$(AP): $(OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) $^ $(LIBS) -o $(AP)

$(CPPOBJS): %.o: %.cpp
	$(CPP) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@
```

**Comment by chenhn123** [comment]
have been modified in v0.9.3
